apiVersion: v1
kind: Namespace
metadata:
  name: hive
---
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: hive
spec:
  ports:
  - port: 9083
  selector:
    app: hive-metastore
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive
spec:
  selector:
    matchLabels:
      app: hive-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - image: bitsondatadev/hive-metastore:latest
        name: hive-metastore
        env:
        - name: METASTORE_DB_HOSTNAME
          value: "mariadb"
        ports:
        - containerPort: 9083
          name: hive-metastore
        volumeMounts:
        - mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/
          name: hive-metastore-config
          readOnly: true
      volumes:
        - name: hive-metastore-config
          configMap:
            name: hive-metastore-config
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:latest
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: metastore_db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-pv
      volumes:
        - name: mariadb-pv
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mariadb
  name: mariadb-pvc
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
