apiVersion: v1
kind: ConfigMap
metadata:
  name: iceberg-catalog
  namespace: iceberg
data:
  iceberg.properties: |
    connector.name=iceberg
    iceberg.catalog.type=rest
    iceberg.rest-catalog.uri=http://rest:8181
    iceberg.rest-catalog.warehouse=s3a://iceberg/warehouse
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.s3.endpoint=http://minio.minio:9000
    hive.s3.region=us-east-1
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-catalog
  namespace: iceberg
data:
  postgres.properties: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgres.postgres:5432/inventory
    connection-user=postgresuser
    connection-password=postgrespw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-catalog
  namespace: iceberg
data:
  mysql.properties: |
    connector.name=mysql
    connection-url=jdbc:mysql://mysql.mysql:3306
    connection-user=root
    connection-password=debezium
