FROM apache/flink:1.16.0
RUN wget https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-mysql-cdc/2.3.0/flink-sql-connector-mysql-cdc-2.3.0.jar -O lib/flink-sql-connector-mysql-cdc-2.3.0.jar
RUN wget https://repo1.maven.org/maven2/com/ververica/flink-sql-connector-postgres-cdc/2.3.0/flink-sql-connector-postgres-cdc-2.3.0.jar -O lib/flink-sql-connector-postgres-cdc-2.3.0.jar
RUN wget https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-elasticsearch7/1.16.0/flink-sql-connector-elasticsearch7-1.16.0.jar -O lib/flink-sql-connector-elasticsearch7-1.16.0.jar

